# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{yogo-datamapper}
  s.version = "0.5.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Ryan Heimbuch"]
  s.date = %q{2010-11-01}
  s.description = %q{Yogo extensions to DataMapper}
  s.email = %q{rheimbuch@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "Gemfile",
     "Gemfile.lock",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "features/step_definitions/yogo-datamapper_steps.rb",
     "features/support/env.rb",
     "features/yogo-datamapper.feature",
     "lib/yogo/datamapper/model/common/properties.rb",
     "lib/yogo/datamapper/model/configuration.rb",
     "lib/yogo/datamapper/model/operations.rb",
     "lib/yogo/datamapper/model/operations/add.rb",
     "lib/yogo/datamapper/model/operations/clear.rb",
     "lib/yogo/datamapper/model/stored/configuration.rb",
     "lib/yogo/datamapper/repository_manager.rb",
     "lib/yogo/datamapper/repository_manager/model.rb",
     "lib/yogo/datamapper/repository_manager/resource.rb",
     "spec/spec_helper.rb",
     "yogo-datamapper.gemspec"
  ]
  s.homepage = %q{http://github.com/yogo/yogo-datamapper}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Yogo extensions to DataMapper}
  s.test_files = [
    "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<data_mapper>, ["~> 1.0.2"])
      s.add_runtime_dependency(%q<dm-is-remixable>, [">= 0"])
      s.add_runtime_dependency(%q<yogo-support>, [">= 0"])
      s.add_runtime_dependency(%q<yogo-operation>, [">= 0"])
    else
      s.add_dependency(%q<data_mapper>, ["~> 1.0.2"])
      s.add_dependency(%q<dm-is-remixable>, [">= 0"])
      s.add_dependency(%q<yogo-support>, [">= 0"])
      s.add_dependency(%q<yogo-operation>, [">= 0"])
    end
  else
    s.add_dependency(%q<data_mapper>, ["~> 1.0.2"])
    s.add_dependency(%q<dm-is-remixable>, [">= 0"])
    s.add_dependency(%q<yogo-support>, [">= 0"])
    s.add_dependency(%q<yogo-operation>, [">= 0"])
  end
end

